apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: devops419845acr.azurecr.io/app:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:        # <-- DODAJEMY TE DWIE LINIJKI
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 8080
      